python test.py target data/pdb_mmcif/mmcif_files/ --uniref90_database_path data/uniref90/uniref90.fasta --model_name model_1_multimer \
    --mgnify_database_path data/mgnify/mgy_clusters_2018_12.fa \
    --use_precomputed_alignments ./alignments/ \
    --pdb70_database_path data/pdb70/pdb70 \
    --uniclust30_database_path data/uniclust30/uniclust30_2018_08/uniclust30_2018_08 \
    --pdb_seqres_database_path data/pdb_seqres/pdb_seqres.txt \
    --uniprot_database_path data/uniprot/uniprot.fasta \
    --output_dir ./tmp/ \
    --bfd_database_path data/bfd/bfd_metaclust_clu_complete_id30_c90_final_seq.sorted_opt \
    --jackhmmer_binary_path `which jackhmmer` \
    --hhblits_binary_path `which hhblits` \
    --hhsearch_binary_path `which hhsearch` \
    --kalign_binary_path `which kalign` \
    --model_device cuda:0
